# Generated by Django 5.1.2 on 2024-10-10 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation', models.CharField(max_length=255, verbose_name='Геолокация (заглушка)')),
                ('address', models.TextField(verbose_name='Адрес кофейни')),
                ('barista_number', models.IntegerField(verbose_name='Число бариста на смене')),
            ],
            options={
                'verbose_name': 'Кофейня',
                'verbose_name_plural': 'Кофейни',
                'ordering': ('barista_number',),
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('courier_category', models.CharField(choices=[('FOOT', 'Пеший курьер'), ('BICYCLE', 'Велокурьер'), ('CAR', 'Автокурьер')], default='CAR', max_length=100, verbose_name='Категория курьера')),
                ('courier_status', models.CharField(choices=[('AT_WORK', 'На работе'), ('RELAXING', 'Отдыхает'), ('BREAK', 'Перерыв')], max_length=100, verbose_name='Категория курьера')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
                'ordering': ('courier_status',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('category', models.CharField(choices=[('DRINK', 'Напиток'), ('DESSERT', 'Десерт'), ('HOT', 'Горячее блюдо')], max_length=100, null=True, verbose_name='Категория товара')),
                ('availability', models.CharField(choices=[('ABSENT', 'Товар отсутствует'), ('AVAILABLE', 'В наличии')], default='AVAILABLE', max_length=100, verbose_name='Наличие')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фотография товара')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('create_date',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('delivery_status', models.CharField(choices=[('PAYING', 'Оплата заказа'), ('PREPARING', 'Заказ готовится'), ('DELIVERING', 'Заказ доставляется'), ('RECEIVED', 'Заказ получен')], default='PAYING', max_length=100, verbose_name='Статус доставки')),
                ('payment_method', models.CharField(choices=[('BANK_CARD', 'Банковская карта')], max_length=100, null=True, verbose_name='Способ оплаты')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('waiting_time', models.TimeField(verbose_name='Время доставки')),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.cafe', verbose_name='Кофейни')),
                ('products', models.ManyToManyField(related_name='orders', to='core.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('waiting_time',),
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_left', models.TimeField(verbose_name='Времени доставки прошло')),
                ('geolocation', models.CharField(max_length=255, verbose_name='Геолокация (заглушка)')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.courier', verbose_name='Курьер')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ('time_left',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('products', models.ManyToManyField(related_name='carts', to='core.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'ordering': ('sum',),
            },
        ),
    ]
