# Generated by Django 5.1.2 on 2024-10-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deliverydescription_delivery_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverydescription',
            options={'ordering': ('id',), 'verbose_name': 'Описание', 'verbose_name_plural': 'Описания'},
        ),
        migrations.AlterField(
            model_name='courier',
            name='courier_status',
            field=models.CharField(choices=[('AT_WORK', 'На работе'), ('RELAXING', 'Отдыхает'), ('BREAK', 'Перерыв')], max_length=100, verbose_name='Статус курьера'),
        ),
    ]
