# Generated by Django 5.1.2 on 2024-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cart_sum_alter_order_sum_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='waiting_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
    ]
