# Generated by Django 5.1.2 on 2024-10-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_waiting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('PAYING', 'Оплата заказа'), ('PREPARING', 'Заказ готовится'), ('DELIVERING', 'Заказ доставляется'), ('RECEIVED', 'Заказ получен')], default='PAYING', max_length=100, null=True, verbose_name='Статус доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма'),
        ),
    ]
